theme = "awesome-identity"
baseURL = "https://rudesome.nl"
title = "➜  ~ whoami"
publishDir = "docs"
disableKinds = ["taxonomy", "term"]

## Profile Configurations
[params.profile]
  portrait = "/images/portrait.png"
  firstname = "Ruud"
  lastname = "Voorjans"
  title = "Cloud / DevOps Engineer"
  location = "Simpelveld"
  bio = """
  I am a DevOps engineer with 10+ years of sysadmin experience. <br> 
In my day job, I have experience in IaC, CI/CD and automation,
am using tools like Terraform, Azure Pipeline, Kubernetes, Ansible <br> <br>
At night am mainly "z-shelling" in the terminal; writing, coding, reading, deploying and learning. <br>
Passionate about Programming and Open Source."""

[params.contacts]
  email = "ruud.voorjans@rudesome.nl"
  github = "rudesome"
  linkedin = "rudesome"

[params.actions.resume]
  name = "Resume"
  url = "/resume"

[params.actions.source]
  name = "Site Source"
  url = "https://github.com/rudesome/rudesome.nl"

## Footer Configurations
[params.footer]
  copyright = """<i class="fab fa-linux"></i> rudesome <i class="fab fa-linux"></i>"""
  poweredBy = false

[markup.goldmark.renderer]
unsafe= true

